# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: procedures.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10procedures.proto\x12\nprocedures\"\x1a\n\x0b\x45\x63hoRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1b\n\x0c\x45\x63hoResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2A\n\x04Ping\x12\x39\n\x04Ping\x12\x17.procedures.EchoRequest\x1a\x18.procedures.EchoResponseB!Z\x1fperryizgr8.com/gorpc/proceduresb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'procedures_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037perryizgr8.com/gorpc/procedures'
  _ECHOREQUEST._serialized_start=32
  _ECHOREQUEST._serialized_end=58
  _ECHORESPONSE._serialized_start=60
  _ECHORESPONSE._serialized_end=87
  _PING._serialized_start=89
  _PING._serialized_end=154
# @@protoc_insertion_point(module_scope)
